server.port=8080

# Mude para validate para proteger a estrutura do seu banco
spring.jpa.hibernate.ddl-auto=validate
# Pode manter como false já que você rodou o script manualmente
spring.flyway.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/inventory
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true